ARCH=sensors.c leds-arch.c sw_uart_basic.c
#serial2spi.c slip-dev.c spi-rdc.c slip-cmds.c radio.c
CONTIKI_TARGET_DIRS = . dev apps
ifndef CONTIKI_TARGET_MAIN
CONTIKI_TARGET_MAIN = contiki-main.c
endif
COFFEE = 1
UIP_CONF_IPV6 = 1
ifdef UIP_CONF_IPV6
CFLAGS += -DWITH_UIP6=1
endif

CONTIKI_TARGET_SOURCEFILES += $(ARCH) $(CONTIKI_TARGET_MAIN) $(CONTIKI_CORE) 
MCU=LM3S6965
include $(CONTIKI)/cpu/arm/lm3s/Makefile.lm3s6965

